var glossaries = {

Ch011_6372_B9780702032257500142cetablefn1: `
<p><a xmlns:epub="http://www.idpf.org/2007/ops" role="doc-noteref" epub:type="noteref" href="#cetablefn1a"><sup>a</sup></a><a id="cenotep1"/>The fifth pharyngeal arch is undeveloped.</p> `,

glo_001: `<h3>Abembryonic pole</h3><p>the part of the blastocyst furthest from the inner cell mass</p> `,
glo_002: `<h3>Accessory renal artery</h3><p>artery(ies) usually supplying the lower pole of the kidney, arising because of the successive vascular supplies as the metanephric kidney ‘rises’ in its development</p> `,
glo_003: `<h3>Accessory ribs</h3><p>non-thoracic ribs, arising from the transverse processes of cervical or lumbar vertebrae</p> `,
glo_004: `<h3>Acrania</h3><p>partial or complete absence of the calvaria or skull bones</p> `,
glo_005: `<h3>Agenesis</h3><p>failure of an embryonic organ or structure to develop</p> `,
glo_006: `<h3>Alar plates</h3><p>the dorsal halves of the developing neural tube, separated from the ventral basal plates by the sulcus limitans</p> `,
glo_007: `<h3>Allantois</h3><p>small outpouching of the endoderm of the yolk sac into the connecting stalk, from which the urachus and thence median umbilical ligament is derived</p> `,
glo_008: `<h3>Amnioblast</h3><p>a cell derived from the ectoderm which forms the wall of the amniotic cavity, i.e. the amnion</p> `,
glo_009: `<h3>Amnion</h3><p>the extra-embryonic membrane that surrounds the developing embryo/fetus</p> `,
glo_010: `<h3>Amniotic bands</h3><p>bands of tissue that detach from the amnion, compressing fetal structures, especially limbs</p> `,
glo_011: `<h3>Amniotic cavity</h3><p>the cavity surrounded by the amnion, filled with amniotic fluid, surrounding the fetus</p> `,
glo_012: `<h3>Amniotic fluid</h3><p>fluid derived from the amnion and from maternal tissue fluid. It is the fluid lost at the time of the ‘breaking of the waters’ prior to birth</p> `,
glo_013: `<h3>Ampulla</h3><p>a flask-like widening of a tube, like the uterine tube</p> `,
glo_014: `<h3>Anal membrane</h3><p>formed at about 7 weeks, as the cloacal membrane is divided by the urorectal septum</p> `,
glo_015: `<h3>Anchoring villi</h3><p>the placental villi that attach the chorionic plate to the decidual tissue</p> `,
glo_016: `<h3>Anencephaly</h3><p>congenital anomaly caused by the failed closure of the anterior neuropore, leading to failure of part or all of the brain to develop</p> `,
glo_017: `<h3>Angiogenic cell cluster</h3><p>a cluster of mesodermal cells that give rise to blood vessels or the heart tubes</p> `,
glo_018: `<h3>Annular pancreas</h3><p>a congenital anomaly resulting from splitting of the ventral pancreatic bud such that the two portions migrate and surround the duodenum, thus forming a ring of tissue constricting the gut tube</p> `,
glo_019: `<h3>Anophthalmos</h3><p>failure of development of the eye</p> `,
glo_020: `<h3>Anterior cardinal vein</h3><p>vein draining the head region of the fetus, into the common cardinal vein and thus into the sinus venosus</p> `,
glo_021: `<h3>Anterior nares</h3><p>openings into the nasal cavity on the face</p> `,
glo_022: `<h3>Anterior neuropore</h3><p>open cranial portion of the neural tube which, after its closure, gives rise to the brain</p> `,
glo_023: `<h3>Aortic arches</h3><p>the series of initially symmetrical arteries within the pharyngeal arches that arise from the truncus arteriosus to supply structures in the head and neck</p> `,
glo_024: `<h3>Aorticopulmonary septum</h3><p>spiral partition dividing the ascending aorta and the pulmonary trunk</p> `,
glo_025: `<h3>Atrioventricular canal</h3><p>the communication between the common atrium and the early ventricle</p> `,
glo_026: `<h3>Atrioventricular groove</h3><p>the external groove in the heart lying between the atria and the ventricles and in which coronary arteries and the coronary sinus is found</p> `,
glo_027: `<h3>Azygos line veins</h3><p>one of the pair of initially symmetrical veins (lying in the future trunk) that form the definitive azygos system of veins</p> `,
glo_028: `<h3>Basal plate</h3><p>the maternal side of the full-term placenta, consisting of the decidua basalis and the syncytiotrophoblast; <i>alternative meaning</i>: the name given to the ventral thickening of the neural tube</p> `,
glo_029: `<h3>Bicornuate uterus</h3><p>a mammalian non-primate pattern in which there are two uterine horns, united by a common cervix; this pattern is a relatively common anomaly in humans</p> `,
glo_030: `<h3>Bilaminar embryonic disc</h3><p>the two adjacent layers of the epiblast/ectoderm and hypoblast/endoderm lying in contact, forming the early embryo</p> `,
glo_031: `<h3>Blastocoele</h3><p>the fluid-filled cavity in the blastocyst</p> `,
glo_032: `<h3>Blastocyst</h3><p>the hollow sphere of cells derived from the morula consisting of the inner cell mass and the outer trophoblast</p> `,
glo_033: `<h3>Blastomere</h3><p>component cells of the dividing zygote during cleavage which retains pluripotentiality and forms the morula</p> `,
glo_034: `<h3>Body cavities</h3><p>serous cavities comprising the pericardial, pleural and peritoneal cavities, all derived from the intra-embryonic coelom</p> `,
glo_035: `<h3>Branchial</h3><p>resembling the branchia (or ‘gills’) of fishes and in the human embryo the branchial or pharyngeal arches give rise to structures in the head and neck</p> `,
glo_036: `<h3>Branchial cyst</h3><p>sometimes as the overgrowing second pharyngeal arch forms a smooth contour to the neck, it encloses a space which is a branchial cyst or a cervical cyst</p> `,
glo_037: `<h3>Branchial fistulae</h3><p>branchial cysts can sometimes become inflamed, and open via a fistula on to the exterior or the pharynx, anterior to the sternocleidomastoid muscle</p> `,
glo_038: `<h3>Branching morphogenesis</h3><p>the developmental mechanism responsible for a branching pattern, e.g. of the dividing lung buds</p> `,
glo_039: `<h3>Buccopharyngeal membrane</h3><p>the place of direct contact between ectoderm and endoderm in the trilaminar embryonic disc which later separates the mouth from the pharynx. It breaks down in week 4, thus establishing communication between the amniotic cavity and the gut tube</p> `,
glo_040: `<h3>Bulboventricular groove</h3><p>the groove lying between the bulbus cordis and the primitive ventricle in the primitive heart tube</p> `,
glo_041: `<h3>Bulbus cordis</h3><p>the part of the heart tube that gives rise to the conus cordis (the outflow tract of the ventricles) and the truncus arteriosus which forms the proximal parts of the aorta and the pulmonary trunk</p> `,
glo_042: `<h3>Cardiac loop</h3><p>the primitive heart tube</p> `,
glo_043: `<h3>Cardiogenic area</h3><p>the area of unsegmented mesoderm in the trilaminar embryonic disc that gives rise to the heart tube</p> `,
glo_044: `<h3>Cartilaginous plate</h3><p>the growth plate in a developing long bone</p> `,
glo_045: `<h3>Caudal</h3><p>the tail end of the embryo</p> `,
glo_046: `<h3>Cephalic</h3><p>the head end of the embryo</p> `,
glo_047: `<h3>Cephalic flexure</h3><p>the bend in the cranial part of the developing neural tube in the region of the future midbrain</p> `,
glo_048: `<h3>Cephalocaudal</h3><p>a term used in relation to the longitudinal (head to tail) folding of the embryo</p> `,
glo_049: `<h3>Cervical flexure</h3><p>the bend in the developing neural tube between the future medulla and the spinal cord</p> `,
glo_050: `<h3>Cervical rib</h3><p>an anomalous rib that develops from the transverse process of the 7th cervical vertebra. It may sometimes put pressure on the lower trunk of the brachial plexus or the subclavian artery</p> `,
glo_051: `<h3>Cervical sinus</h3><p>a space formed by the 2nd, 3rd and 4th pharyngeal clefts enclosed by the overgrowth of the second pharyngeal arch which normally disappears. If it doesn’t, a cyst may arise</p> `,
glo_052: `<h3>Chordoma</h3><p>a malignant tumour of the remnants of the notochord</p> `,
glo_053: `<h3>Chorion</h3><p>the membrane that surrounds the fetus, consisting of trophoblast and extra-embryonic mesoderm</p> `,
glo_054: `<h3>Chorion frondosum</h3><p>that part of the chorion that is the fetal contribution to the placenta</p> `,
glo_055: `<h3>Chorion laeve</h3><p>smooth abembryonic wall of the chorion which has lost its villi during the 2nd month. Fuses with the deciduas parietalis and amnion</p> `,
glo_056: `<h3>Chorionic plate</h3><p>the extra-embryonic mesoderm that lines the cytotrophoblast, thus bordering the chorionic cavity</p> `,
glo_057: `<h3>Chorionic villi</h3><p>the finger-like protrusions of chorion and trophoblast which contain blood vessels, and are surrounded by maternal blood in the intervillous spaces that allow placental exchange</p> `,
glo_058: `<h3>Choroidal fissure</h3><p>the groove that forms after the invagination of the optic vesicle and the lens placode on the undersurface of the developing eye</p> `,
glo_059: `<h3>Cleft lip</h3><p>a congenital anomaly in which there is a split in the upper lip, due to failure of fusion of the components that normally make up the lip. The condition is often associated with a cleft palate</p> `,
glo_060: `<h3>Cleft palate</h3><p>a congenital anomaly in which the palatal folds that normally fuse in the midline to separate the oral and nasal cavities remain separated; thus there is free communication between the two cavities</p> `,
glo_061: `<h3>Cloacal fold</h3><p>seen in the indifferent stage of genital development, the pair of mesenchymal elevations between the genital tubercle and the anal fold, lying around the cloacal membrane</p> `,
glo_062: `<h3>Cloacal membrane</h3><p>the thin membrane that separates the cloaca from the amniotic cavity; it is divided into an anterior urogenital membrane and a posterior anal membrane by the arrival of the urorectal septum</p> `,
glo_063: `<h3>Cloacal plate</h3><p>located at the caudal end of the trilaminar embryonic disc, where there is no intervening mesoderm between the ectoderm and endoderm. The plate becomes the cloacal membrane but later breaks down to allow free communication between urogenital structures and the amniotic cavity, and thus the exterior</p> `,
glo_064: `<h3>Coloboma iridis</h3><p>a congenital anomaly where the choroid fissure fails to close at the 7th week, and results in a cleft in the iris</p> `,
glo_065: `<h3>Common cardinal veins</h3><p>the veins in the embryo that receive the anterior and posterior cardinal veins and drain into the sinus venosus</p> `,
glo_066: `<h3>Conceptus</h3><p>the resulting assembly of tissues at any stage from a fertilized ovum to birth</p> `,
glo_067: `<h3>Congenital cataract</h3><p>when the lens becomes opaque in utero, usually due to genetic reasons, but can result after maternal rubella infection during pregnancy</p> `,
glo_068: `<h3>Congenital deafness</h3><p>various structural defects of the middle or inner ear, often caused for genetic reasons, though may follow maternal rubella infection during pregnancy</p> `,
glo_069: `<h3>Congenital detachment of retina</h3><p>where the outer pigment layer of the retina and the neural layer, initially separated by the intraretinal space, fail to fuse, thus resulting in a detached retina</p> `,
glo_070: `<h3>Conus cordis</h3><p>the part of the developing heart tube comprising the outflow tracts of the heart, derived from the bulbus cordis, and leading to the truncus arteriosus</p> `,
glo_071: `<h3>Corpus luteum</h3><p>the remnants of tissue of the Graffian follicle, after the oocyte has left during ovulation, which secretes progesterone</p> `,
glo_072: `<h3>Cotyledons</h3><p>components of the placenta formed after 4–5 months, divided into 15–20 structural units (intervillous spaces) by decidual septa</p> `,
glo_073: `<h3>Cranial</h3><p>the head end of the embryo</p> `,
glo_074: `<h3>Craniopharyngiomas</h3><p>usually benign tumours of the pituitary gland derived from the part arising from Rathke’s pouch (ectodermal from stomodaeum). They may cause pituitary dysfunction and/or hydrocephalus</p> `,
glo_075: `<h3>Craniosynostosis</h3><p>premature closure of one or more of the skull sutures</p> `,
glo_076: `<h3>Crista terminalis</h3><p>the internal ridge in the wall of the right atrium separating the roughened auricular wall from the smooth-walled part derived from the sinus venosus (the sinus venarum)</p> `,
glo_077: `<h3>Cytotrophoblast</h3><p>the cellular part of the trophoblast, as distinguished from the syncytiotrophoblast</p> `,
glo_078: `<h3>Cytotrophoblast shell</h3><p>the outer layer of cytotrophoblast that attaches to the decidual plate</p> `,
glo_079: `<h3>Decidua basalis</h3><p>the part of the deciduae that attaches to the cytotrophoblastic shell</p> `,
glo_080: `<h3>Decidua capsularis</h3><p>the part of the deciduae that covers the abembryonic pole of the implantation site, fusing with the chorion laeve and amnion</p> `,
glo_081: `<h3>Decidua parietalis</h3><p>the part of the deciduae that lines the uterine lumen not involved with implantation</p> `,
glo_082: `<h3>Decidualization</h3><p>the process of differentiation of uterine stromal cells following implantation</p> `,
glo_083: `<h3>Decidual reaction</h3><p>the process of differentiation of uterine stromal cells following implantation</p> `,
glo_084: `<h3>Dermatome</h3><p>the embryonic structure derived from a somite that contributes, on a segmental basis, to the dermis</p> `,
glo_085: `<h3>Dermomyotome</h3><p>the embryonic structure derived from a somite that splits into a dermatome and a myotome</p> `,
glo_086: `<h3>Diaphysis</h3><p>the developing centre of ossification in the shaft of a long bone in endochondral ossification</p> `,
glo_087: `<h3>Diencephalon</h3><p>the secondary brain vesicle derived from the forebrain that gives rise to the thalamus and hypothalamus</p> `,
glo_088: `<h3>Dizygotic</h3><p>of two zygotes, term often used in relation to two twins arising from two separate oocytes</p> `,
glo_089: `<h3>Dorsal mesentery</h3><p>the tissue derived from the lateral plate mesoderm that suspends the gut tube from the dorsal wall of the embryo</p> `,
glo_090: `<h3>Dorsal mesocardium</h3><p>the membrane that initially suspends the heart tube in the developing pericardial cavity</p> `,
glo_091: `<h3>Dorsal mesogastrium</h3><p>the part of the dorsal mesentery that suspends the stomach</p> `,
glo_092: `<h3>Dorsal pancreatic bud</h3><p>the bud of pancreatic tissue derived from foregut endoderm that contributes the larger component to the adult pancreas</p> `,
glo_093: `<h3>Ductus arteriosus</h3><p>the embryonic vessel that connects the pulmonary trunk to the arch of the aorta, thus providing a means for oxygenated blood to reach the systemic circulation without the need to pass through the lungs</p> `,
glo_094: `<h3>Ductus venosus</h3><p>the embryonic vessel that lies on the visceral surface of the developing liver and acts as a bypass, thus enabling oxygenated blood in the umbilical vein to gain access to the inferior vena cava (and hence the systemic circulation) without passing through the liver</p> `,
glo_095: `<h3>Dysplasia</h3><p>abnormal development</p> `,
glo_096: `<h3>Dysplasia of joints</h3><p>malformation of joints, sometimes caused by pressure of a developing joint against the uterine wall</p> `,
glo_097: `<h3>Ectoderm</h3><p>the outer germ cell layer that gives rise to the epidermis of the skin, the nervous system and sense organs</p> `,
glo_098: `<h3>Ectodermal placodes</h3><p>the thickened plate of ectoderm from which sense organs develop</p> `,
glo_099: `<h3>Ectopic</h3><p>at a site other than the normal one</p> `,
glo_100: `<h3>Embryonic period</h3><p>from the 3rd to the 8th week of development, during which the embryo is most sensitive to teratogens, and when the organ systems are being formed</p> `,
glo_101: `<h3>Endocardial cushions</h3><p>mesenchymal structures arising around the atrioventricular canal that divide the latter to form separate channels for the right and left sides of the heart between the atria and ventricles</p> `,
glo_102: `<h3>Endochondral</h3><p>bone formation from a cartilage model</p> `,
glo_103: `<h3>Endoderm</h3><p>the inner germ layer from which the lining of the gut tube and its associated glandular structures are derived</p> `,
glo_104: `<h3>Endolymphatic sac</h3><p>develops as part of the membranous labyrinth of the inner ear</p> `,
glo_105: `<h3>Endometrium</h3><p>the inner lining of the uterus in which implantation occurs</p> `,
glo_106: `<h3>Enteric</h3><p>related to the gut (or enteron), or intestines</p> `,
glo_107: `<h3>Epaxial</h3><p>situated upon or above an axis. The dorsal epimeres of myotomes that give rise to epaxial muscles, the erector spinae muscles</p> `,
glo_108: `<h3>Epiblast</h3><p>forms the ectoderm germ layer in the early embryo</p> `,
glo_109: `<h3>Epimere</h3><p>the myotomes give rise to dorsal epimeres which give rise to epaxial muscles, the erector spinae muscles</p> `,
glo_110: `<h3>Epiphyseal</h3><p>related to the cartilaginous epiphyseal growth plate at which longitudinal growth takes place in a long bone</p> `,
glo_111: `<h3>Epiphysis</h3><p>the ossification centre of the cartilaginous model of a long bone</p> `,
glo_112: `<h3>Epispadias</h3><p>congenital anomaly where the urethral opening is on the dorsal surface of the penis and is associated with exstrophy of the urinary bladder</p> `,
glo_113: `<h3>Exocoelomic membrane</h3><p>the membrane derived from the endoderm that forms the wall of the primitive yolk sac and lines the extra-embryonic coelom</p> `,
glo_114: `<h3>Exstrophy of the urinary bladder</h3><p>where the mucosa of the urinary bladder is open to the exterior via a defect in the future ventral abdominal wall of the embryo. Always associated with epispadias</p> `,
glo_115: `<h3>Extra-embryonic coelom</h3><p>the space between the layers of the extra-embryonic mesoderm; also known as the chorionic cavity, and separates the amnion and yolk sac from the embryo</p> `,
glo_116: `<h3>Extrahepatic biliary atresia</h3><p>congenital obliteration of parts of the biliary tract potentially causing liver failure if not corrected surgically</p> `,
glo_117: `<h3>Fetal membranes</h3><p>amnion, chorion, allantois and yolk sac</p> `,
glo_118: `<h3>Fetal period</h3><p>the period of growth in size of the fetus from week 8 to term</p> `,
glo_119: `<h3>Floating villi</h3><p>the terminations of chorionic villi that branch off the main stem tertiary villi</p> `,
glo_120: `<h3>Fontanelles</h3><p>the spaces lying between the flat bones of the fetal skull filled by connective tissue, often referred to as ‘soft spots’</p> `,
glo_121: `<h3>Foramen caecum</h3><p>the depression in the apex of the sulcus terminalis of the tongue that marks the origin of the thyroid gland</p> `,
glo_122: `<h3>Foramen ovale</h3><p>the hole in the atrial septum in the embryo and fetus allowing oxygenated placental blood in the right side of the heart to pass to the left without going through the pulmonary circulation. Normally this hole closes immediately after birth, forming the fossa ovalis</p> `,
glo_123: `<h3>Forebrain</h3><p>the most cranial part of the developing brain which gives rise to the cerebral hemispheres and the thalamus and hypothalamus</p> `,
glo_124: `<h3>Fossa ovalis</h3><p>the depression in the atrial septum marking the site of the closed foramen ovale</p> `,
glo_125: `<h3>Frontonasal prominence</h3><p>the mesenchymal elevation ventral to the brain vesicles, contributing to the face and constitutes the upper border of the stomodaeum</p> `,
glo_126: `<h3>Gastroschisis</h3><p>the herniation of the abdominal contents directly through the wall into the amniotic cavity, in which the organs are not invested by amnion or peritoneum</p> `,
glo_127: `<h3>Gastrulation</h3><p>the process of establishment of the three germ layers</p> `,
glo_128: `<h3>Genital swellings</h3><p>mesenchymal elevations on either side of the cloacal folds in an indifferent embryo. These become the labia majora in the female or scrotum in the male</p> `,
glo_129: `<h3>Genital tubercle</h3><p>the forerunner of the glans penis in the male or clitoris in the female</p> `,
glo_130: `<h3>Gonadal ridges</h3><p>elevations of intermediate mesoderm beneath the coelomic epithelium in the early embryo that give rise to the gonads</p> `,
glo_131: `<h3>Gubernaculum</h3><p>the band of mesenchyme along which the gonad descends to its definitive adult location</p> `,
glo_132: `<h3>Hepatic diverticulum</h3><p>the endodermal bud from the foregut that forms the liver</p> `,
glo_133: `<h3>Hepatocardiac channels</h3><p>venous channels in the fetal liver derived from the two vitelline veins, and draining blood from the ductus venosus to the future inferior vena cava</p> `,
glo_134: `<h3>Hiatal hernia</h3><p>congenital herniation of the stomach through the oesophageal hiatus in the diaphragm</p> `,
glo_135: `<h3>Hindbrain</h3><p>the most caudal part of the developing brain that gives rise to the pons and cerebellum, and the medulla oblongata</p> `,
glo_136: `<h3>Horseshoe kidney</h3><p>a congenital anomaly of the kidney whereby usually the lower poles fuse across the midline, giving rise to a horseshoe-like appearance</p> `,
glo_137: `<h3>Human chorionic gonadotrophin (HCG)</h3><p>a hormone produced by the syncytiotrophoblast in sufficient quantities by the end of the 2nd week that it may be detected in urine of pregnant women, thus constituting a test for pregnancy</p> `,
glo_138: `<h3>Hydrocephalus</h3><p>excessive buildup of cerebrospinal fluid leading to enlarged ventricles of the brain, a compressed cerebral cortex and an enlarged skull unless the excess fluid is surgically drained</p> `,
glo_139: `<h3>Hydrocoele</h3><p>a congenital anomaly of the scrotum in which fluid collects within the tunica vaginalis</p> `,
glo_140: `<h3>Hypaxial</h3><p>the myotomes give rise to the ventral hypomeres that give rise to hypaxial muscles which include body wall musculature and limb musculature</p> `,
glo_141: `<h3>Hypoblast</h3><p>gives rise to the endoderm germ layer in the early embryo</p> `,
glo_142: `<h3>Hypobranchial eminence</h3><p>median swelling in floor of future pharynx, formed from the mesoderm of the second, third and part of the fourth pharyngeal arches; also known as the copula, and contributes to posterior third of tongue</p> `,
glo_143: `<h3>Hypomere</h3><p>formed from myotomes and gives rise to lateral and ventral musculature of abdominal and thoracic wall, plus the limb musculature</p> `,
glo_144: `<h3>Hypospadias</h3><p>incomplete fusion of the urethral folds in the male leading to opening of the penile urethra along its ventral surface</p> `,
glo_145: `<h3>Intermaxillary segment</h3><p>formed by growth and fusion of parts of the two medial nasal processes and resulting in formation of the philtrum of upper lip and primary palate</p> `,
glo_146: `<h3>Intermediate mesoderm</h3><p>part of the intra-embryonic mesoderm that gives rise to components of the urogenital system</p> `,
glo_147: `<h3>Intermediate villi</h3><p>parts of the chorionic villi</p> `,
glo_148: `<h3>Intervillous spaces</h3><p>blood-filled spaces between the anchoring chorionic villi arising from the trophoblastic lacunae</p> `,
glo_149: `<h3>Intra-embryonic coelom</h3><p>spaces within the intra-embryonic mesoderm that merge to form the future serous cavities of the trunk</p> `,
glo_150: `<h3>Intra-embryonic mesoderm</h3><p>the middle layer in the trilaminar disc and the last of the three germ layers of the embryo to form</p> `,
glo_151: `<h3>Intramembranous ossification</h3><p>ossification process that takes place within mesenchyme (membrane) rather than from a cartilage model</p> `,
glo_152: `<h3>Labioscrotal swellings</h3><p>arise from the genital swellings located on either side of the urethral folds</p> `,
glo_153: `<h3>Lacunae</h3><p>spaces, hollows or cavities</p> `,
glo_154: `<h3>Lateral lingual swellings</h3><p>derived from first arch mesoderm which, together with the median tuberculum impar, form the anterior two-thirds of the tongue</p> `,
glo_155: `<h3>Lateral nasal processes</h3><p>swellings on the outside of the nasal pits that give rise to the lateral side of the nose</p> `,
glo_156: `<h3>Lateral plate mesoderm</h3><p>most lateral part of intra-embryonic mesoderm that gives rise to the splanchnic and somatic layers: the future visceral and parietal serous membranes of the trunk</p> `,
glo_157: `<h3>Lens placode</h3><p>thickening of surface ectoderm around forebrain from which the lens vesicle forms</p> `,
glo_158: `<h3>Lens vesicle</h3><p>invagination of the surface ectoderm from which the lens develops</p> `,
glo_159: `<h3>Levator glandulae thyroideae</h3><p>lower end of the thyroglossal duct which sometimes gives rise to smooth muscle</p> `,
glo_160: `<h3>Ligamentum arteriosum</h3><p>fibrosed remnant of the ductus arteriosus connecting the pulmonary trunk and the ascending aorta</p> `,
glo_161: `<h3>Ligamentum teres (hepatis)</h3><p>fibrosed remnant of the left umbilical vein connecting the umbilicus and the porta hepatis</p> `,
glo_162: `<h3>Ligamentum venosum</h3><p>fibrosed remnant of the ductus venosus which connects the portal vein to the inferior vena cava</p> `,
glo_163: `<h3>Lobster claw (hand or foot)</h3><p>abnormal cleft between the second and fourth metacarpal bones and associated soft tissues, with the third bone missing, thus resembling a lobster’s claw</p> `,
glo_164: `<h3>Macrostomia</h3><p>a congenital defect in which there is a large mouth</p> `,
glo_165: `<h3>Mandibular prominence or process</h3><p>lower part of the first pharyngeal arch that gives rise to lower jaw; contains Meckel’s cartilage which disappears</p> `,
glo_166: `<h3>Mantle layer</h3><p>part of the developing neural tube closest to the central canal from which grey matter arises</p> `,
glo_167: `<h3>Marginal zone</h3><p>part of the most peripheral layer of the developing neural tube from which the white matter develops</p> `,
glo_168: `<h3>Maxillary prominence or process</h3><p>upper part of the first pharyngeal arch that gives rise to the upper jaw</p> `,
glo_169: `<h3>Meckel’s cartilage</h3><p>the cartilaginous part of the lower part of the first pharyngeal arch that disappears, though part of it persists as the sphenomandibular ligament and the malleus and incus</p> `,
glo_170: `<h3>Meckel’s diverticulum</h3><p>the persisting remnant of the vitello-intestinal duct which if inflamed can give rise to symptoms mimicking appendicitis</p> `,
glo_171: `<h3>Medial nasal processes</h3><p>swellings that form the midline portion of the external nose, and the philtrum of the upper lip</p> `,
glo_172: `<h3>Meningocoele</h3><p>spina bifida in which the meninges protrude through a dorsal defect in the vertebral canal</p> `,
glo_173: `<h3>Meningomyelocoele</h3><p>spina bifida in which the meninges and spinal cord tissues protrude through a dorsal defect in the vertebral canal</p> `,
glo_174: `<h3>Mesencephalon</h3><p>one of the primary brain vesicles that gives rise to the midbrain</p> `,
glo_175: `<h3>Mesenchyme</h3><p>loose embryonic connective tissue derived from mesoderm or neural crest</p> `,
glo_176: `<h3>Mesoduodenum</h3><p>the dorsal mesentery associated with the duodenum</p> `,
glo_177: `<h3>Mesonephric duct</h3><p>duct of the mesonephros which in males partly persists as the ductus deferens, forms the trigone of the urinary bladder, and the ureteric bud of the metanephros</p> `,
glo_178: `<h3>Mesonephros</h3><p>the primitive kidney that precedes the development of the metanephros, the definitive adult kidney</p> `,
glo_179: `<h3>Metanephric blastema</h3><p>caudal part of the nephrogenic cord of the intermediate mesoderm into which the ureteric bud grows; the blastema gives rise to the nephrons</p> `,
glo_180: `<h3>Metanephric diverticulum</h3><p>ureteric buds</p> `,
glo_181: `<h3>Metanephros</h3><p>the forerunner of the definitive adult kidney that begins in the pelvic region and ‘ascends’ to its adult lumbar position</p> `,
glo_182: `<h3>Metencephalon</h3><p>the secondary brain vesicle that gives rise to the pons and cerebellum, arising from the rhombencephalon</p> `,
glo_183: `<h3>Microcephaly</h3><p>congenital defect in which the brain fails to develop and the head is small</p> `,
glo_184: `<h3>Microphthalmia</h3><p>a small eyeball</p> `,
glo_185: `<h3>Microstomia</h3><p>congenital defect in which there is a small mouth</p> `,
glo_186: `<h3>Monozygotic</h3><p>term related to identical twins in which a single ovum gives rise to two individuals</p> `,
glo_187: `<h3>Morula</h3><p>the result of the mitotic divisions of the zygote prior to the formation of the blastocyst</p> `,
glo_188: `<h3>Muscular dystrophy</h3><p>congenital myopathy leading to muscle degeneration and weakness</p> `,
glo_189: `<h3>Myelencephalon</h3><p>the secondary brain vesicle that gives rise to the medulla, arising from the rhombencephalon</p> `,
glo_190: `<h3>Myoblast</h3><p>precursor cells of muscle, derived from intra-embryonic mesoderm</p> `,
glo_191: `<h3>Myotome</h3><p>part of a somite that gives rise to somatic muscle</p> `,
glo_192: `<h3>Nasal pits</h3><p>openings derived from the nasal placodes</p> `,
glo_193: `<h3>Nasal placodes</h3><p>invaginations from the surface ectoderm giving rise to nasal pits</p> `,
glo_194: `<h3>Nasal sacs</h3><p>deepenings of the nasal pits forming the nasal cavities</p> `,
glo_195: `<h3>Nasolacrimal groove</h3><p>the deep furrow separating the medial and lateral nasal prominences, and from which the nasolacrimal duct forms</p> `,
glo_196: `<h3>Nephric vesicle</h3><p>the early tubule into which the glomeruli invaginate, and which links up with the duct system of the developing kidney</p> `,
glo_197: `<h3>Nephrogenic cord</h3><p>intermediate mesoderm tissue that gives rise to pro-, meso- and metanephric tissues</p> `,
glo_198: `<h3>Neural crest</h3><p>apical portion of the neural groove, budding off prior to formation of the neural tube; gives rise to a wide range of structures including components of the peripheral and autonomic nervous system</p> `,
glo_199: `<h3>Neural crest cells</h3><p>neuroectodermal cells forming the neural crest</p> `,
glo_200: `<h3>Neural folds</h3><p>edges of the neural groove, the apical edges of which meet in the midline to form the neural tube</p> `,
glo_201: `<h3>Neural groove</h3><p>the midline furrow in surface ectoderm which differentiates to form the neural tube</p> `,
glo_202: `<h3>Neural plate</h3><p>the slipper-shaped enlargement of the surface ectoderm which rounds up, initially forming the neural groove and then the neural tube</p> `,
glo_203: `<h3>Neural tube</h3><p>the forerunner of the brain and spinal cord</p> `,
glo_204: `<h3>Neuroblasts</h3><p>cells of the mantle zone of the developing neural tube that give rise to neurons</p> `,
glo_205: `<h3>Neurocranium</h3><p>the skull, including its vault and base</p> `,
glo_206: `<h3>Neuroectoderm</h3><p>the specialized part of the surface ectoderm that gives rise to the neural tube and associated nervous structures</p> `,
glo_207: `<h3>Neuroepithelial cells</h3><p>cells of the neuroepithelial layer</p> `,
glo_208: `<h3>Neuroepithelial layer</h3><p>cells that give rise to the rest of the wall of the neural tube, and itself differentiates into the ependymal cells lining the tube</p> `,
glo_209: `<h3>Neurulation</h3><p>the process of neural tube formation</p> `,
glo_210: `<h3>Notochord</h3><p>the midline structure that forms a midline axis for the embryo, and from which the intervertebral discs are formed</p> `,
glo_211: `<h3>Notochordal plate</h3><p>cells arising from the primitive pit to form the cylinder which becomes the notochord</p> `,
glo_212: `<h3>Oblique facial cleft</h3><p>result from the failure of the maxillary prominence to fuse with its partner lateral nasal prominence</p> `,
glo_213: `<h3>Occipital myotomes</h3><p>myotomes in the occipital region of the embryo, some of which give rise to the musculature of the tongue</p> `,
glo_214: `<h3>Oesophageal atresia</h3><p>failure of the oesophagus to develop</p> `,
glo_215: `<h3>Oesophageal hernia</h3><p>a form of diaphragmatic hernia in which upper parts of the stomach are located above the diaphragm because of congenital shortness of the oesophagus, and hence there may be a constriction in the stomach</p> `,
glo_216: `<h3>Omphalocele</h3><p>herniation of abdominal contents through the umbilical ring, covered by amnion</p> `,
glo_217: `<h3>Optic cup</h3><p>double-walled invagination of the optic vesicle</p> `,
glo_218: `<h3>Optic stalk</h3><p>the stalk-like hollow evagination of part of the forebrain which produces the cup-like retina into which the lens vesicle fits</p> `,
glo_219: `<h3>Oronasal membrane</h3><p>separates the oral cavity from the future nasal cavity before the membrane breaks down</p> `,
glo_220: `<h3>Ostium primum</h3><p>the first opening in the developing atrial septum that disappears as the septum primum reaches the endocardial cushion</p> `,
glo_221: `<h3>Ostium secundum</h3><p>second foramen to form in the upper part of the septum primum which forms the foramen ovale of the atrial septum</p> `,
glo_222: `<h3>Otic placode</h3><p>thickening of ectoderm on each side of the hindbrain from which the otic vesicle forms</p> `,
glo_223: `<h3>Otic vesicle</h3><p>invagination of the otic placode from which the inner ear develops</p> `,
glo_224: `<h3>Ovum</h3><p>fertilized secondary oocyte</p> `,
glo_225: `<h3>Paired heart tubes</h3><p>endocardial tubes formed from mesenchymal angiogenic cell clusters that fuse to form a single heart tube after folding of the embryo</p> `,
glo_226: `<h3>Paramesonephric ducts</h3><p>paired ducts derived from the coelomic epithelium; fuse in the midline to form the uterus and uterine tubes</p> `,
glo_227: `<h3>Paraxial mesoderm</h3><p>mesodermal cells close to the midline between the ectoderm and the endoderm, from which somites arise</p> `,
glo_228: `<h3>Parenchymal</h3><p>the functional, cellular component of an organ</p> `,
glo_229: `<h3>Parietal</h3><p>of the body walls (paries = wall, Latin)</p> `,
glo_230: `<h3>Pelvic kidney</h3><p>congenital condition in which the developing kidney does not undergo ‘ascent’ to achieve its adult position and remains in the pelvis</p> `,
glo_231: `<h3>Pericardioperitoneal canals</h3><p>part of the intra-embryonic coelom from which the pleural cavities develop</p> `,
glo_232: `<h3>Pharyngeal arches</h3><p>5–6 paired mesodermal structures in the developing pharyngeal wall from which certain components of the head and neck are derived</p> `,
glo_233: `<h3>Physiological umbilical hernia</h3><p>protrusion of part of the developing intestinal loop into the umbilicus during elongation and rotation of the midgut</p> `,
glo_234: `<h3>Placenta previa</h3><p>a placenta that develops over the internal os of the uterus</p> `,
glo_235: `<h3>Placental septa</h3><p>partitions of the placenta formed by decidual tissue, thus resulting in 15–20 cotyledons (compartments in the placenta)</p> `,
glo_236: `<h3>Pleuropericardial folds</h3><p>membranes that separate the pericardial cavity from the pleural cavities</p> `,
glo_237: `<h3>Pleuroperitoneal membranes</h3><p>folds that separate the future pleural from the peritoneal cavities</p> `,
glo_238: `<h3>Pluripotential</h3><p>potential of developing in more than one way, or a number of fixed points of differentiation</p> `,
glo_239: `<h3>Polydactyly</h3><p>congenital condition in which additional digits on hands or feet develop</p> `,
glo_240: `<h3>Polyhydramnios</h3><p>an excess of amniotic fluid possibly resulting from an inability of the fetus to swallow as a consequence of oesophageal atresia</p> `,
glo_241: `<h3>Posterior neuropore</h3><p>caudal opening in the neural tube which closes on the 27th day</p> `,
glo_242: `<h3>Primary brain vesicles</h3><p>three dilatations at the cranial end of the neural tube that give rise to the secondary brain vesicles and thence the cerebrum, cerebellum and brain stem</p> `,
glo_243: `<h3>Primary chorionic villi</h3><p>trophoblastic projections in the developing placenta. Gaseous exchange will occur after the appearance of a mesenchymal core (secondary villi) in which blood vessels develop (tertiary villi)</p> `,
glo_244: `<h3>Primary yolk sac</h3><p>formed by the lining of the endoderm cells which migrate around the lower portion of the blastocyst cavity</p> `,
glo_245: `<h3>Primitive cloaca</h3><p>endoderm-derived cavity at the terminal part of the hindgut which forms the rectum and upper anal canal, and the urinary bladder</p> `,
glo_246: `<h3>Primitive node</h3><p>rim of ectoderm at the cranial end of the primitive streak giving rise to the notochord</p> `,
glo_247: `<h3>Primitive pit</h3><p>a depression located around the primitive node</p> `,
glo_248: `<h3>Primitive sex cords</h3><p>structures in the presumptive gonads that come to be occupied by the primordial germ cells that migrate from the yolk sac</p> `,
glo_249: `<h3>Primitive streak</h3><p>a linear midline structure derived from epiblast/ectoderm whose migrating cells form the mesoderm germ layer</p> `,
glo_250: `<h3>Primitive urogenital sinus</h3><p>the ventral component resulting from the partitioning of the cloaca comprising the urinary bladder and urethra</p> `,
glo_251: `<h3>Primordia</h3><p>the beginning formations of a structure</p> `,
glo_252: `<h3>Primordial germ cells</h3><p>cells that migrate from the wall of the yolk sac to occupy the sex cords in the gonads and give rise to either oogonia or spermatogonia</p> `,
glo_253: `<h3>Probe patency of the foramen ovale</h3><p>a common developmental anomaly in which there is incomplete sealing of the foramen ovale, such that it is possible to pass a probe from one atrial chamber to the other</p> `,
glo_254: `<h3>Processus vaginalis</h3><p>the part of the peritoneal cavity that precedes the testis through the inguinal canal, and into which the testis invaginates. Later in development the processus becomes the tunica vaginalis</p> `,
glo_255: `<h3>Prochordal plate</h3><p>an area at the cranial end of the embryonic disc where there is contact between the ectoderm and the endoderm, and no intervening mesoderm. The forerunner of the buccopharyngeal membrane</p> `,
glo_256: `<h3>Proctodaeum</h3><p>the ectodermal depression from the surface ectoderm that forms the lower part of the anal canal</p> `,
glo_257: `<h3>Pronephros</h3><p>first primitive kidney formation that disappears completely, superseded by the mesonephros and thence the metanephros</p> `,
glo_258: `<h3>Prosencephalon</h3><p>primary brain vesicle from which the telencephalon and diencephalon form</p> `,
glo_259: `<h3>Pulmonary hypoplasia</h3><p>underdevelopment of the lung in which there is a reduced number of air sacs or alveoli</p> `,
glo_260: `<h3>Rachischisis</h3><p>spina bifida in which neural fold tissue remains open on the dorsal surface of the back</p> `,
glo_261: `<h3>Rathke’s pouch</h3><p>an ectodermal outpocketing of the stomodeum (the ectodermal part of the lining of the oral cavity) from which the anterior lobe of the pituitary develops</p> `,
glo_262: `<h3>Respiratory distress syndrome</h3><p>condition in which the alveoli collapse due to lack of surfactant production by the type II alveolar epithelial cells</p> `,
glo_263: `<h3>Respiratory diverticulum</h3><p>outpouching of the foregut endoderm that gives rise to the epithelial lining and glands of the trachea and bronchial tree</p> `,
glo_264: `<h3>Rhombencephalon</h3><p>most caudal of the three primary cerebral vesicles that gives rise to the metencephalon (pons and cerebellum) and the myelencephalon (medulla)</p> `,
glo_265: `<h3>Rostral</h3><p>relating to the beak, or in humans the nose; term used to define a position at the head end of the embryo</p> `,
glo_266: `<h3>Scaphocephaly</h3><p>an abnormally long and narrow skull due to premature closing of the sagittal suture, with centres of ossification in the suture line</p> `,
glo_267: `<h3>Sclerotome</h3><p>derived from the somite and giving rise to connective tissue surrounding the neural tube and notochord to form the vertebrae</p> `,
glo_268: `<h3>Secondary chorionic villi</h3><p>placental villi whose core contains mesenchymal tissue</p> `,
glo_269: `<h3>Secondary yolk sac</h3><p>derived from the overgrowth of endodermal cells around the wall of the primary yolk sac</p> `,
glo_270: `<h3>Sensorineuronal deafness</h3><p>a hearing loss due to a lesion in the cochlea or in the auditory nerve or its pathway to the brain, sometimes caused by maternal rubella infection at the time of pregnancy</p> `,
glo_271: `<h3>Septum primum</h3><p>a sickle-shaped growth in the roof of the common atrium that extends towards the endocardial cushions, leaving the opening of the foramen primum</p> `,
glo_272: `<h3>Septum secundum</h3><p>a second crescent-shaped fold forming part of the developing atrial septum, after the appearance of the septum primum. Together the two septa form the atrial septum</p> `,
glo_273: `<h3>Septum transversum</h3><p>unsegmented mesoderm that develops initially cranial to the prochordal plate, and gives rise to part of the diaphragm, the fibrous pericardium, and connective tissues of the liver. It migrates from its original position in the cervical region of the embryo to its adult position</p> `,
glo_274: `<h3>Sinus venarum</h3><p>the smooth-walled part of the developing right atrium</p> `,
glo_275: `<h3>Sinus venosus</h3><p>the venous channel that drains blood into the heart from the embryo and the placenta. Initially, it is a symmetrical structure having two horns, but with time it loses its symmetry, and the numbers of veins that drain into it. In the adult only the coronary sinus, the smooth part of the right atrium, and the proximal portion of the inferior vena cava persist</p> `,
glo_276: `<h3>Sinuvaginal bulbs</h3><p>endodermal swellings from the posterior wall of the urogenital sinus forming the lower part of the vagina</p> `,
glo_277: `<h3>Somatic mesoderm</h3><p>derived from the lateral plate mesoderm and forming the serous membrane associated with the body wall</p> `,
glo_278: `<h3>Somatopleure</h3><p>somatic lateral plate mesoderm</p> `,
glo_279: `<h3>Somites</h3><p>most medial segmented components differentiated from the paraxial mesoderm and giving rise to muscle of the trunk and limbs, most of the axial skeleton and part of the dermis</p> `,
glo_280: `<h3>Spina bifida cystica</h3><p>a neural tube defect in which the neural tube and/or surrounding membranes protrude through a deficient vertebral arch posteriorly, forming a cyst-like structure and resulting in neurological deficits</p> `,
glo_281: `<h3>Spina bifida occulta</h3><p>a less severe form of spinal bifida in which the neural tube tissue remains in its normal location, but with a deficient posterior vertebral arch. The defect is often marked by an overlying patch of hairy skin</p> `,
glo_282: `<h3>Splanchnic mesoderm</h3><p>lateral plate mesoderm that gives rise to the serous membranes covering viscera (splanchnic = pertaining to organs)</p> `,
glo_283: `<h3>Splanchopleure</h3><p>splanchnic lateral plate mesoderm</p> `,
glo_284: `<h3>Sternal bars</h3><p>bars of cartilage (sternebrae) from which the sternum develops</p> `,
glo_285: `<h3>Stomodaeum</h3><p>ectodermal invagination forming part of the oral cavity, and bordering with the endodermal-lined portion which is the pharynx</p> `,
glo_286: `<h3>Subcardinal</h3><p>term used in relation to one of the longitudinal veins draining the body of the embryo that is incorporated into the inferior vena cava</p> `,
glo_287: `<h3>Sulcus limitans</h3><p>the longitudinal groove that separates the alar and basal plates of the parts of the neural tube that give rise to the derivatives of the diencephalon (thalamus and hypothalamus), brainstem and spinal cord</p> `,
glo_288: `<h3>Sulcus terminalis</h3><p>the groove on the exterior of the heart that marks the crista terminalis, demarcating the smooth-walled from the roughened parts of the right atrium</p> `,
glo_289: `<h3>Supracardinal</h3><p>term used in relation to one of the longitudinal veins draining the body of the embryo that becomes part of the azygos system</p> `,
glo_290: `<h3>Surfactant</h3><p>the phospholipid substance produced by type II alveolar cells that reduces surface tension at the air : alveolar interface and thus facilitates respiration</p> `,
glo_291: `<h3>Syncytiotrophoblast</h3><p>the outer part of the trophoblast that invades the endometrium and which contributes to the formation of the placenta</p> `,
glo_292: `<h3>Syncytium</h3><p>a cellular structure containing many nuclei</p> `,
glo_293: `<h3>Telencephalon</h3><p>one of the pair of secondary cerebral vesicles from the forebrain that gives rise to the cerebral hemispheres</p> `,
glo_294: `<h3>Teratogen</h3><p>an agent that can cause a birth defect</p> `,
glo_295: `<h3>Tertiary villi</h3><p>a chorionic villus that has blood vessels in its core</p> `,
glo_296: `<h3>Thyroglossal duct</h3><p>duct leading from the apex of the sulcus terminalis of the tongue at the foramen caecum to the developing thyroid gland. Sometimes this duct persists in part of its course, giving rise to ectopic thyroid tissue</p> `,
glo_297: `<h3>Thyroglossal fistula</h3><p>an abnormal connection of the thyroglossal duct to the exterior</p> `,
glo_298: `<h3>Thyroid diverticulum</h3><p>the endodermal bud of tissue migrating from the foramen caecum to form the thyroid gland</p> `,
glo_299: `<h3>Tracheo-oesophagal fistula</h3><p>an abnormal communication between the developing oesophagus and trachea</p> `,
glo_300: `<h3>Trimester</h3><p>time division of gestation into thirds, each about three months</p> `,
glo_301: `<h3>Truncoconal swellings</h3><p>develop in the conus cordis and the truncus arteriosus to form the aortico-pulmonary septum which divides the ascending aorta and the pulmonary trunk</p> `,
glo_302: `<h3>Tuberculum impar</h3><p>midline swelling in the floor of the pharynx derived from the first pharyngeal arch mesoderm and contributes to the anterior two-thirds of the tongue</p> `,
glo_303: `<h3>Tubotympanic recess</h3><p>first pharyngeal pouch that further develops as the auditory tube</p> `,
glo_304: `<h3>Ultimobranchial body</h3><p>derived from the lower part of the fourth (sometimes considered to be the fifth) pharyngeal pouch from which the parafollicular or ‘C’ cells of the thyroid gland develop</p> `,
glo_305: `<h3>Umbilical arteries</h3><p>blood vessels bringing deoxygenated blood to the placenta from the fetus</p> `,
glo_306: `<h3>Umbilical cord</h3><p>the composite of structures linking the fetus with the placenta. Contains the yolk sac remnants, vitelline duct remnants, and umbilical vessels, and is covered by amnion</p> `,
glo_307: `<h3>Umbilical veins</h3><p>blood vessels bringing oxygenated blood to the fetus from the placenta. Only the left umbilical vein persists and after birth it becomes the ligamentum teres of the liver</p> `,
glo_308: `<h3>Urachus</h3><p>the fibrous cord that connects the urinary bladder to the umbilicus. It arises from the allantois; if this remains patent urachal sinuses, cysts or fistulae may result</p> `,
glo_309: `<h3>Uterovaginal canal</h3><p>fused paramesonephric ducts that becomes the uterus and the upper part of the vagina</p> `,
glo_310: `<h3>Ureteric bud</h3><p>develops from the caudal end of the mesonephric duct growing into the nephrogenic cord with which it forms the metanephros</p> `,
glo_311: `<h3>Urethral folds</h3><p>arise from the cloacal folds forming the labia minora in females and the shaft of the penis in males</p> `,
glo_312: `<h3>Urogenital membrane</h3><p>the anterior half of the cloacal membrane that covers the urogenital openings, and later breaks down</p> `,
glo_313: `<h3>Urogenital ridge</h3><p>derived from the intermediate mesoderm bulging into the coelomic cavity from which kidneys, ureters and parts of the reproductive system develop</p> `,
glo_314: `<h3>Urogenital sinus</h3><p>anterior division of the cloaca giving rise to the urinary bladder and the urethra</p> `,
glo_315: `<h3>Urorectal septum</h3><p>mesodermal tissue that partitions the cloaca into a ventral urogenital sinus and a dorsal anorectal canal</p> `,
glo_316: `<h3>Uteroplacental circulation</h3><p>the circulation in which the transport of substances between the maternal and fetal blood occurs across the walls of the chorionic villi</p> `,
glo_317: `<h3>Ventral mesentery</h3><p>the mesentery associated with the foregut derived from the septum transversum</p> `,
glo_318: `<h3>Ventral pancreatic bud</h3><p>the smaller of the two buds of endodermal tissue from the foregut that gives rise to part of the head and the uncinate process of the pancreas</p> `,
glo_319: `<h3>Visceral</h3><p>organ or viscus, thus visceral relating to an organ</p> `,
glo_320: `<h3>Viscerocranium</h3><p>bones that give rise to the face mainly derived from the first two pharyngeal arches</p> `,
glo_321: `<h3>Vitelline duct</h3><p>the connection between the yolk sac and the midgut. Sometimes a proximal portion of it persists as Meckel’s diverticulum</p> `,
glo_322: `<h3>Vitelline veins</h3><p>veins draining the yolk sac, some of which become the drainage of the gut, as branches of the hepatic portal vein</p> `,
glo_323: `<h3>Vitello-intestinal duct</h3><p>vitelline duct</p> `,
glo_324: `<h3>Volvulus</h3><p>a twisting of the intestines with a risk of cutting off blood supply</p> `,
glo_325: `<h3>Zona pellucida</h3><p>the thick membrane that surrounds an oocyte</p> `,
tit1: `<p><sup>*</sup> Banking that organizes large, complex financial transactions such as mergers or initial.</p>`,
BIBu1: `<p>Morgon JP. <cite>Accelerated testing&#8212;statistical models, test plans, and data analyses</cite> Westminster, CO: Hobbs Engineering; 1990.</p>`,
BIB1: `<p>1. Morgon JP. <cite>Accelerated testing&#8212;statistical models, test plans, and data analyses</cite> Westminster, CO: Hobbs Engineering; 1990.</p>`,
bib_B1: `<p>Cyriax J. <cite>Textbook of orthopaedic medicine</cite>. In: <cite><i>Diagnosis of Soft Tissue Lesions</i></cite>. 8th ed. Vol 1. London: Balliere Tindall; 1982.</p>`,
bib_B2: `<p>Weed L. <cite>Medical records that guide and teach: part I</cite>. <cite><i>N Engl J Med</i></cite>. 1968;278:593-600.</p>`,


}

